[tool.poetry]
name = "llm-sbi"
version = "0.1.0"
description = "LLM Sanitization-By-Intent"
authors = ["Aaron Johnston <aaron.johnston001@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
